# модуль предназначени для возврата тестовых данных 
# эмулируя сервер СУТП при работе программ в режиме ТЕСТ

import json

# возвращаем тестовые данные,
# которые обычно возвращает сервер СУТП
#  по API-ссылке в url_api
def requestSUTPTest(url_api:str):
    # возвращает список:
    # [0]-статус выполнения:"0"-ошибка, "1"-успешно
    # [1]-словесное описание статуса
    # [2]-тестовые данные или пустая строка при ошибке

    
    # словарь с API-ссылками
    # 1: статистика о кол-ве ПУ,прошедших через ОТК за дату
    # 2: статистика о выполненной работе всеми сотрудниками
    # 3: списке дефектов для указанного девайса 
    #   (история о ремонтах ПУ)
    # 4: история по всем статусам ПУ
    # 5: информация о ПУ по техническому или серийному номеру
    # 6: весь список статусов ПУ на 07.05.2024
    # 7: информации о пользователе по табельному номеру
    # 8: количество устройств, прошедших через указанный 
    #    этап (21) сегодня
    # 9: список ПУ, с которыми работал указанный работник.
    #    Выводит номер ПУ, статс ПУ, на который он был 
    #    переведен, дата создания записи
    # 10: информация о заказе (на 20.05.2024)

    url_dict = {"/api/Device/QCPassedDeviceNumbers/Date=":"url1",
                "/api/Employee/EmployeesHistory/Date=":"url2",
                "/RepairCycle/Get/TechNumber=":"url3",
                "/DeviceHistory/Get/TechNumber=":"url4",
                "/DeviceHistory/Get/SerialNumber=":"url4",
                "api/Device/":"url5",
                "/api/Device/BySerialNumber/":"url5",
                "/api/NSI/DeviceStatus/all":"url6",
                "/api/Employee/": "url7",
                "/api/Device/CountDevicesPassedSector": "url8",
                "/DeviceHistory/GetByEmplyeeId/EmployeeId=": "url9",
                "/api/Order/": "url10"}
    
    # Определим метку из словаря ссылок по выходному API-url
    # сформируем список из ключей словаря
    keys_list=list(url_dict.keys())
    # переберем список ключей
    for key in keys_list:
        # если наименование ключа имеется в API-ссылке
        if key in url_api:
            # получим метку
            url_mark = url_dict[key]
            # выйдем из for key
            break
    # если вышли не по break
    else:
        # выйдем из ПП с ошибкой
        return ["0","Тестовых данных нет.",""]
    
    # если нужна статистика о кол-ве ПУ,прошедших через ОТК за дату
    if url_mark=="url1":
        val_sutp=[
            {"operation":"ОТК пройден", 
                "type":"0008-i-prom.1-Y....",
                "techNumber":"100234"},
            {"operation":"ОТК пройден", 
                "type":"0008-i-prom.1-Y....", 
                "techNumber":"100235"},
            {"operation": "ОТК пройден",
                "type": "0009-i-prom.1-Y....",
                "techNumber": "100242"},
            {"operation": "Дефект", 
                "type": "0008-i-prom.1-Y....", 
                "techNumber": "100236"},
            {"operation":"В ремонте на линии", 
                "type":"0008-i-prom.1-Y....", 
                "techNumber":"100237"},
            {"operation":"Дефект", 
                "type":"0008-i-prom.1-Y....", 
                "techNumber":"100238"},
            {"operation":"В ремонте на линии", 
                "type":"0114-i-prom.1-Y....", 
                "techNumber":"100239"},
            {"operation":"В ремонте на линии", 
                "type":"0008-i-prom.1-Y....", 
                "techNumber":"100240"},
            {"operation":"Дефект", 
                "type":"0114-i-prom.1-Y....", 
                "techNumber":"100241"},
            {"operation":"В ремонте на линии", 
                "type":"0114-i-prom.1-Y....", 
                "techNumber":"100247"},
            {"operation": "Отправлен в неизвестность",
                "type": "0008-i-prom.1-Y....", 
                "techNumber": "100248"},
            {"operation": "другой статус",
                "type": "0008-i-prom.1-Y....", 
                "techNumber": "100247"}
            ]
    # если нужна статистика о выполненной работе всеми сотрудниками
    elif url_mark=="url2":
        null = None
        val_sutp = [
            {
                "name": "Школина Юлия Викторовна",
                "statusId": 8,
                "selfType": "d",
                "operation": "Стыковка и паспортизация пройдены",
                "operationPriority": 10,
                "operationWithPriority": "10 - Стыковка и паспортизация пройдены",
                "quantity": 29,
                "elementType": "i-prom.3-3-1-1/2-S-RG-Y-Y",
                "codeElementType": "0114",
                "orderNumber": "-"
            },
            {
                "name": "Школина Юлия Викторовна",
                "statusId": 8,
                "selfType": "d",
                "operation": "Стыковка и паспортизация пройдены",
                "operationPriority": 10,
                "operationWithPriority": "10 - Стыковка и паспортизация пройдены",
                "quantity": 540,
                "elementType": "i-prom.3-3-1-1/2-S-RG-Y-Y",
                "codeElementType": "0114",
                "orderNumber": "00000062"
            },
            {
                "name": "Минневалиев Ильяс Альтапович",
                "statusId": 7,
                "selfType": "d",
                "operation": "Отправил с ремонта: Гравировка пройдена",
                "operationPriority": 8,
                "operationWithPriority": "08 - Отправил с ремонта: Гравировка пройдена",
                "quantity": 2,
                "elementType": "i-prom.3-3T-2-0,5S/1-P-RF-N-N",
                "codeElementType": "0203",
                "orderNumber": "-"
            },
            {
                "name": "Минневалиев Ильяс Альтапович",
                "statusId": 7,
                "selfType": "d",
                "operation": "Отправил с ремонта: Гравировка пройдена",
                "operationPriority": 8,
                "operationWithPriority": "08 - Отправил с ремонта: Гравировка пройдена",
                "quantity": 1,
                "elementType": "i-prom.3-3T-2-0,5S/1-P-RF-N-N",
                "codeElementType": "0203",
                "orderNumber": "00000062"
            },
            {
                "name": "Милятчева Юлия Викторовна",
                "statusId": 10,
                "selfType": "d",
                "operation": "Отправил с ремонта: Гравировка пройдена",
                "operationPriority": null,
                "operationWithPriority": "В ремонте на линии",
                "quantity": 9,
                "elementType": "i-prom.3-3-1-1/2-S-RG-Y-Y",
                "codeElementType": "0114",
                "orderNumber": "00000062"
            },
            {
                "name": "Милятчева Юлия Викторовна",
                "statusId": 21,
                "selfType": "d",
                "operation": "ОТК пройден",
                "operationPriority": 9,
                "operationWithPriority": "09 - ОТК пройден",
                "quantity": 103,
                "elementType": "i-prom.3-3-1-1/2-S-RG-Y-Y",
                "codeElementType": "0114",
                "orderNumber": "00000062"
            },
            {
                "name": "Милятчева Юлия Викторовна",
                "statusId": 10,
                "selfType": "d",
                "operation": "В ремонте на линии",
                "operationPriority": null,
                "operationWithPriority": "В ремонте на линии",
                "quantity": 1,
                "elementType": "i-prom.3-3-1-1/2-S-RG-Y-Y",
                "codeElementType": "0114",
                "orderNumber": "00000126"
            },
            {
                "name": "Милятчева Юлия Викторовна",
                "statusId": 21,
                "selfType": "d",
                "operation": "ОТК пройден",
                "operationPriority": 9,
                "operationWithPriority": "09 - ОТК пройден",
                "quantity": 35,
                "elementType": "i-prom.3-3-1-1/2-S-RG-Y-Y",
                "codeElementType": "0114",
                "orderNumber": "-"
            },
            {
                "name": "Милятчева Юлия Викторовна",
                "statusId": 21,
                "selfType": "d",
                "operation": "ОТК пройден",
                "operationPriority": 9,
                "operationWithPriority": "09 - ОТК пройден",
                "quantity": 48,
                "elementType": "i-prom.3-3-1-1/2-S-RG-Y-Y",
                "codeElementType": "0114",
                "orderNumber": "00000091"
            },
            {
                "name": "Милятчева Юлия Викторовна",
                "statusId": 10,
                "selfType": "d",
                "operation": "В ремонте на линии",
                "operationPriority": null,
                "operationWithPriority": "В ремонте на линии",
                "quantity": 3,
                "elementType": "i-prom.3-3-1-1/2-S-RG-Y-Y",
                "codeElementType": "0114",
                "orderNumber": "00000091"
            },
            {
                "name": "Милятчева Юлия Викторовна",
                "statusId": 10,
                "selfType": "d",
                "operation": "В ремонте на линии",
                "operationPriority": null,
                "operationWithPriority": "В ремонте на линии",
                "quantity": 4,
                "elementType": "i-prom.3-3-1-1/2-S-RG-Y-Y",
                "codeElementType": "0114",
                "orderNumber": "-"
            },
            {
                "name": "Сафиуллина Рамиля Шамилевна",
                "statusId": 21,
                "selfType": "d",
                "operation": "ОТК пройден",
                "operationPriority": 9,
                "operationWithPriority": "09 - ОТК пройден",
                "quantity": 121,
                "elementType": "i-prom.3-3-1-1/2-S-RG-Y-Y",
                "codeElementType": "0114",
                "orderNumber": "00000062"
            },
            {
                "name": "Сафиуллина Рамиля Шамилевна",
                "statusId": 10,
                "selfType": "d",
                "operation": "В ремонте на линии",
                "operationPriority": null,
                "operationWithPriority": "В ремонте на линии",
                "quantity": 4,
                "elementType": "i-prom.3-3-1-1/2-S-RG-Y-Y",
                "codeElementType": "0114",
                "orderNumber": "00000062"
            },
            {
                "name": "Сафиуллина Рамиля Шамилевна",
                "statusId": 399,
                "selfType": "d",
                "operation": "Дефект",
                "operationPriority": null,
                "operationWithPriority": "Дефект",
                "quantity": 1,
                "elementType": "i-prom.3-3-1-1/2-S-RG-Y-Y",
                "codeElementType": "0114",
                "orderNumber": "-"
            },
            {
                "name": "Сафиуллина Рамиля Шамилевна",
                "statusId": 10,
                "selfType": "d",
                "operation": "В ремонте на линии",
                "operationPriority": null,
                "operationWithPriority": "В ремонте на линии",
                "quantity": 8,
                "elementType": "i-prom.3-3-1-1/2-S-RG-Y-Y",
                "codeElementType": "0114",
                "orderNumber": "00000091"
            },
            {
                "name": "Сафиуллина Рамиля Шамилевна",
                "statusId": 21,
                "selfType": "d",
                "operation": "ОТК пройден",
                "operationPriority": 9,
                "operationWithPriority": "09 - ОТК пройден",
                "quantity": 29,
                "elementType": "i-prom.3-3-1-1/2-S-RG-Y-Y",
                "codeElementType": "0114",
                "orderNumber": "-"
            },
            {
                "name": "Сафиуллина Рамиля Шамилевна",
                "statusId": 21,
                "selfType": "d",
                "operation": "ОТК пройден",
                "operationPriority": 9,
                "operationWithPriority": "09 - ОТК пройден",
                "quantity": 74,
                "elementType": "i-prom.3-3-1-1/2-S-RG-Y-Y",
                "codeElementType": "0114",
                "orderNumber": "00000091"
            },
            {
                "name": "Сафиуллина Рамиля Шамилевна",
                "statusId": 10,
                "selfType": "d",
                "operation": "В ремонте на линии",
                "operationPriority": null,
                "operationWithPriority": "В ремонте на линии",
                "quantity": 2,
                "elementType": "i-prom.3-3-1-1/2-S-RG-Y-Y",
                "codeElementType": "0114",
                "orderNumber": "-"
            },
            {
                "name": "Сафиуллина Рамиля Шамилевна",
                "statusId": 21,
                "selfType": "d",
                "operation": "ОТК пройден",
                "operationPriority": 9,
                "operationWithPriority": "09 - ОТК пройден",
                "quantity": 1,
                "elementType": "i-prom.3-3-1-1/2-S-RG-Y-Y",
                "codeElementType": "0114",
                "orderNumber": "00000084"
            },
            {
                "name": "Фахрутдинова Ирина Витальевна",
                "statusId": 21,
                "selfType": "d",
                "operation": "ОТК пройден",
                "operationPriority": 9,
                "operationWithPriority": "09 - ОТК пройден",
                "quantity": 36,
                "elementType": "i-prom.3-3-1-1/2-S-RG-Y-Y",
                "codeElementType": "0114",
                "orderNumber": "-"
            },
            {
                "name": "Фахрутдинова Ирина Витальевна",
                "statusId": 21,
                "selfType": "d",
                "operation": "ОТК пройден",
                "operationPriority": 9,
                "operationWithPriority": "09 - ОТК пройден",
                "quantity": 41,
                "elementType": "i-prom.3-3-1-1/2-S-RG-Y-Y",
                "codeElementType": "0114",
                "orderNumber": "00000091"
            },
            {
                "name": "Фахрутдинова Ирина Витальевна",
                "statusId": 10,
                "selfType": "d",
                "operation": "В ремонте на линии",
                "operationPriority": null,
                "operationWithPriority": "В ремонте на линии",
                "quantity": 5,
                "elementType": "i-prom.3-3-1-1/2-S-RG-Y-Y",
                "codeElementType": "0114",
                "orderNumber": "-"
            },
            {
                "name": "Фахрутдинова Ирина Витальевна",
                "statusId": 21,
                "selfType": "d",
                "operation": "ОТК пройден",
                "operationPriority": 9,
                "operationWithPriority": "09 - ОТК пройден",
                "quantity": 5,
                "elementType": "i-prom.3-3-1-1/2-S-RG-Y-Y",
                "codeElementType": "0114",
                "orderNumber": "00000084"
            },
            {
                "name": "Фахрутдинова Ирина Витальевна",
                "statusId": 10,
                "selfType": "d",
                "operation": "В ремонте на линии",
                "operationPriority": null,
                "operationWithPriority": "В ремонте на линии",
                "quantity": 1,
                "elementType": "i-prom.3-3-1-1/2-S-RG-Y-Y",
                "codeElementType": "0114",
                "orderNumber": "00000084"
            },
            {
                "name": "Абросимова Гульчачак Магфуровна",
                "statusId": 21,
                "selfType": "d",
                "operation": "ОТК пройден",
                "operationPriority": 9,
                "operationWithPriority": "09 - ОТК пройден",
                "quantity": 125,
                "elementType": "i-prom.1-1-1/2-M-RM-Y-Y",
                "codeElementType": "0008",
                "orderNumber": "00000126"
            },
            {
                "name": "Абросимова Гульчачак Магфуровна",
                "statusId": 21,
                "selfType": "d",
                "operation": "ОТК пройден",
                "operationPriority": 9,
                "operationWithPriority": "09 - ОТК пройден",
                "quantity": 122,
                "elementType": "i-prom.1-1-1/2-M-RM-Y-Y",
                "codeElementType": "0008",
                "orderNumber": "00000133"
            },
            {
                "name": "Жаркова Юлия Владимировна",
                "statusId": 21,
                "selfType": "d",
                "operation": "ОТК пройден",
                "operationPriority": 9,
                "operationWithPriority": "09 - ОТК пройден",
                "quantity": 153,
                "elementType": "i-prom.1-1-1/2-M-RM-Y-Y",
                "codeElementType": "0008",
                "orderNumber": "00000133"
            },
            {
                "name": "Жаркова Юлия Владимировна",
                "statusId": 21,
                "selfType": "d",
                "operation": "ОТК пройден",
                "operationPriority": 9,
                "operationWithPriority": "09 - ОТК пройден",
                "quantity": 125,
                "elementType": "i-prom.1-1-1/2-M-RM-Y-Y",
                "codeElementType": "0008",
                "orderNumber": "00000126"
            },
        ]
    # если нужна история о ремонтах ПУ
    elif url_mark=="url3":
        null=None
        val_sutp={"status":"Success",
                  "message":"Запрос Get успешно выполнен",
                  "items":[{
                      "id":"681b8c5a-738d-4119-84de-c46d3699369f",
                      "techNumber":100025776,
                      "isComplete":True,
                      "gsmModuleDefects":[],
                      "deviceDefects":[
                        {"id":"e4521102-efb0-40e0-880c-98923cff041a",
                          "description":"кривой дисплей",
                          "repairCycleId":"681b8c5a-738d-4119-84de-c46d3699369f",
                          "defectId":"5f0745b8-029b-4559-a711-7b5b65a3390f",
                          "defect":{
                              "id":"5f0745b8-029b-4559-a711-7b5b65a3390f",
                              "name":"Другое",
                              "description":null,
                              "commented":True,
                              "priority":1000000,
                              "defectTypeId":"f0a381a8-e396-4ed6-ba63-8a149a031d74",
                              "defectType":null,
                              "formOfDeviceTypeId": "d317f4ed-7d67-40e5-93c7-800526b075fa",
                              "formOfDeviceType":null,
                              "deviceDefects":[null],
                              "createDate":"2023-10-03T04:56:52.182315Z",
                              "updateDate":null},
                            "createdEmployeeId":379,
                            "createdEmployee":null,
                            "fixedEmployeeId":295,
                            "fixedEmployee":null,
                            "createDate":"2024-04-03T10:43:35.055714Z",
                            "fixDate":"2024-08-14T09:38:11.738298Z",
                            "updateDate":"2024-08-14T09:38:11.776591Z"},
                        {"id":"f4138872-6f6d-4ea9-9f06-94dc84b37d56",
                         "description":null,
                         "repairCycleId":"681b8c5a-738d-4119-84de-c46d3699369f",
                         "defectId":"7321d6fe-5f85-41ff-b584-c61e0c034949",
                         "defect":{
                             "id":"7321d6fe-5f85-41ff-b584-c61e0c034949",
                             "name":"Кривой дисплей",
                             "description":null,
                             "commented":False,
                             "priority":11,
                             "defectTypeId":"8ab1d516-5920-4225-9aca-514c5c6a989d",
                             "defectType":null,
                             "formOfDeviceTypeId":"d317f4ed-7d67-40e5-93c7-800526b075fa",
                             "formOfDeviceType":null,
                             "deviceDefects":[null],
                             "createDate":"2023-10-04T08:22:25.118374Z",
                             "updateDate":null},
                             "createdEmployeeId":273,
                             "createdEmployee":null,
                             "fixedEmployeeId":295,
                             "fixedEmployee":null,
                             "createDate":"2024-02-01T08:55:28.922007Z",
                             "fixDate":"2024-08-14T09:38:11.738298Z",
                             "updateDate":"2024-08-14T09:38:11.776578Z"}
                        ],
                        "description":"кривой дисплей",
                        "grade":2,
                        "createdEmployeeId":379,
                        "completedEmployeeId":295,
                        "createDate":"2024-04-03T10:43:35.055714Z",
                        "completeDate":"2024-08-14T09:38:11.738298Z",
                        "updateDate":"2024-08-14T09:38:11.776591Z"}
                        ],
                "count":1}
    #  если нужна история по всем статусам ПУ
    elif url_mark=="url4":
        val_sutp={'status': 'Success', 'message': 'Запрос Get успешно выполнен', 
            'items': [{'techNumber': 100025776, 'techNumberStr': '100025776', 'packId': 120, 
                       'number': '240100080015919', 'orderNumber': 126, 'order': {'number': 126, 
                        'orderName': '5119 Энергоинновации, ПУ 1ф_GSM- 5200 шт, ПУ 3ф_GSM- 6647 шт',
                          'numberStr': '00000126', 'documentNumber': '5119', 
                          'customerName': 'Энергоинновации', 
                          'responsibleManager': 'Косматкина Е.', 
                          'createDate': '2024-03-12T06:21:41Z', 
                          'isDomestic': False}, 'deviceStatusId': 10, 
                          'deviceStatus': 
                          {'id': 10, 'name': 'В ремонте на линии. Пришел со статуса Гравировка пройдена'}, 
                          'deviceTypeId': 9, 
                          'deviceType': {'id': 9, 'code': '0008', 'name': 'i-prom.1-1-1/2-M-RM-Y-Y'}, 
                          'technologyTypeId': 9, 'employeeId': 379, 
                          'employee': {'id': 379, 'idStr': '3.0379', 'name': 'Юлия', 
                                       'surName': 'Милятчева', 'secondName': 'Викторовна', 
                                       'role': 'user', 'positionId': 3}, 
                            'developmentId': 1, 
                            'development': {'id': 1, 'name': 'Главное предприятие'}, 
                            'validFrom': '2024-04-03T10:43:35.075029Z', 
                            'validTo': '0001-01-01T00:00:00', 
                            'version': 17, 'createDate': '0001-01-01T00:00:00'}, 
                            {'techNumber': 100025776, 'techNumberStr': '100025776', 
                             'packId': 120, 'number': '240100080015919', 'orderNumber': 126, 
                             'order': {'number': 126, 
                                'orderName': '5119 Энергоинновации, ПУ 1ф_GSM- 5200 шт, ПУ 3ф_GSM- 6647 шт', 
                                'numberStr': '00000126', 'documentNumber': '5119', 
                                'customerName': 'Энергоинновации', 
                                'responsibleManager': 'Косматкина Е.', 
                                'createDate': '2024-03-12T06:21:41Z', 
                                'isDomestic': False}, 'deviceStatusId': 7, 
                                'deviceStatus':
                                  {'id': 7, 'name': 'Гравировка пройдена'}, 
                                  'deviceTypeId': 9, 
                                  'deviceType': {'id': 9, 'code': '0008', 'name': 'i-prom.1-1-1/2-M-RM-Y-Y'}, 
                                  'technologyTypeId': 9, 'employeeId': 375, 
                                  'employee': {'id': 375, 'idStr': '3.0375', 'name': 'Кирилл', 
                                               'surName': 'Шатров', 'secondName': 'Андреевич', 
                                               'role': 'user', 'positionId': 3}, 
                                               'developmentId': 1, 
                                               'development': {'id': 1, 'name': 'Главное предприятие'}, 
                                               'validFrom': '2024-04-02T12:33:17.99849Z', 
                                               'validTo': '2024-04-03T10:43:35.075604Z', 
                                               'version': 16, 'createDate': '0001-01-01T00:00:00'}, 
                                    {'techNumber': 100025776, 'techNumberStr': '100025776', 
                                     'packId': 120, 'number': '240100080015919', 
                                     'orderNumber': 126, 
                                     'order': {'number': 126, 
                                    'orderName': '5119 Энергоинновации, ПУ 1ф_GSM- 5200 шт, ПУ 3ф_GSM- 6647 шт',
                                      'numberStr': '00000126', 'documentNumber': '5119', 
                                      'customerName': 'Энергоинновации', 'responsibleManager': 'Косматкина Е.',
                                        'createDate': '2024-03-12T06:21:41Z', 'isDomestic': False}, 
                                        'deviceStatusId': 11, 
                                        'deviceStatus': {'id': 11, 'name': 'Крышка закрыта'}, 
                                        'deviceTypeId': 9, 
                                        'deviceType': {'id': 9, 'code': '0008',
                                         'name': 'i-prom.1-1-1/2-M-RM-Y-Y'}, 'technologyTypeId': 9, 
                                         'employeeId': 363, 
                                         'employee': {'id': 363, 'idStr': '2.0363', 'name': 'Артем', 
                                                      'surName': 'Третьяк', 'secondName': 'Витальевич', 
                                                      'role': 'admin', 'positionId': 2}, 
                                                      'developmentId': 1, 
                                                      'development': {'id': 1, 'name': 'Главное предприятие'}, 
                                                      'validFrom': '2024-04-02T12:15:32.364272Z', 
                                                      'validTo': '2024-04-02T12:33:17.999148Z', 
                                                      'version': 15, 'createDate': '0001-01-01T00:00:00'}, 
                                        {'techNumber': 100025776, 'techNumberStr': '100025776', 
                                        'packId': 120, 'number': '240100080015919', 
                                        'orderNumber': 126, 
                                        'order': {'number': 126, 
                                                  'orderName': '5119 Энергоинновации, ПУ 1ф_GSM- 5200 шт, ПУ 3ф_GSM- 6647 шт', 
                                                  'numberStr': '00000126', 'documentNumber': '5119', 
                                                  'customerName': 'Энергоинновации', 'responsibleManager': 'Косматкина Е.', 
                                                  'createDate': '2024-03-12T06:21:41Z', 'isDomestic': False}, 
                                                  'deviceStatusId': 6, 'deviceStatus': {'id': 6, 'name': 'Калибровка пройдена'}, 
                                                  'deviceTypeId': 9, 
                                                  'deviceType': {'id': 9, 'code': '0008', 'name': 'i-prom.1-1-1/2-M-RM-Y-Y'}, 
                                                  'technologyTypeId': 9, 'employeeId': 268, 
                                                  'employee': {'id': 268, 'idStr': '3.0268', 'name': 'Анастасия', 
                                                               'surName': 'Малюткина', 'secondName': 'Владимировна',
                                                                 'role': 'user', 'positionId': 3}, 
                                                                 'developmentId': 1, 
                                                                 'development': {'id': 1, 'name': 'Главное предприятие'}, 
                                                                 'defectDescription': '', 
                                                                 'validFrom': '2024-04-02T05:21:06.151063Z', 
                                                                 'validTo': '2024-04-02T12:15:32.364892Z',
                                                                 'version': 14, 'createDate': '0001-01-01T00:00:00'}, 
                {'techNumber': 100025776, 'techNumberStr': '100025776', 'packId': 120, 
                 'number': '240100080015919', 'orderNumber': 126, 
                 'order': {'number': 126, 'orderName': '5119 Энергоинновации, ПУ 1ф_GSM- 5200 шт, ПУ 3ф_GSM- 6647 шт', 
                           'numberStr': '00000126', 'documentNumber': '5119', 
                           'customerName': 'Энергоинновации', 
                           'responsibleManager': 'Косматкина Е.', 
                           'createDate': '2024-03-12T06:21:41Z', 
                           'isDomestic': False}, 'deviceStatusId': 5, 
                           'deviceStatus': {'id': 5, 'name': 'Функциональное тестирование пройдено'}, 
                           'deviceTypeId': 9, 
                           'deviceType': {'id': 9, 'code': '0008', 'name': 'i-prom.1-1-1/2-M-RM-Y-Y'}, 
                           'technologyTypeId': 9, 'employeeId': 268, 
                           'employee': {'id': 268, 'idStr': '3.0268', 'name': 'Анастасия', 'surName': 'Малюткина', 
                                        'secondName': 'Владимировна', 'role': 'user', 'positionId': 3}, 
                                        'developmentId': 1, 'development': {'id': 1, 'name': 'Главное предприятие'}, 
                                        'defectDescription': 'Functional testing completed', 
                                        'validFrom': '2024-04-01T12:31:20.18806Z', 'validTo': '2024-04-02T05:21:06.151659Z', 
                                        'version': 13, 'createDate': '0001-01-01T00:00:00'},
                 {'techNumber': 100025776, 'techNumberStr': '100025776', 'packId': 120, 'number': '240100080002463', 
                  'deviceStatusId': 4, 
                  'deviceStatus': {'id': 4, 'name': 'Прошивка пройдена'}, 
                  'deviceTypeId': 9, 'deviceType': {'id': 9, 'code': '0008', 'name': 'i-prom.1-1-1/2-M-RM-Y-Y'}, 
                  'technologyTypeId': 9, 'employeeId': 234, 
                  'employee': {'id': 234, 'idStr': '2.0234', 'name': 'Олег', 'surName': 'Демин', 'secondName': 'Владимирович', 
                               'role': 'admin', 'positionId': 2}, 'developmentId': 1, 
                               'development': {'id': 1, 'name': 'Главное предприятие'}, 
                               'validFrom': '2024-04-01T08:24:45.97179Z', 'validTo': '2024-04-01T12:31:20.188647Z', 
                               'version': 12, 'createDate': '0001-01-01T00:00:00'}, 
                {'techNumber': 100025776, 'techNumberStr': '100025776', 'packId': 120, 'number': '240100080002463',
                  'deviceStatusId': 1000, 'deviceStatus': {'id': 1000, 'name': 'Неизвестный статус'},
                    'deviceTypeId': 9, 
                    'deviceType': {'id': 9, 'code': '0008', 'name': 'i-prom.1-1-1/2-M-RM-Y-Y'}, 'technologyTypeId': 9, 
                    'employeeId': 273, 
                    'employee': {'id': 273, 'idStr': '3.0273', 'name': 'Адиля', 'surName': 'Миннубаева', 
                                 'secondName': 'Гумаровна', 'role': 'user', 'positionId': 3}, 
                                 'developmentId': 1, 
                                 'development': {'id': 1, 'name': 'Главное предприятие'}, 
                                 'validFrom': '2024-02-01T08:55:29.795Z', 
                                 'validTo': '2024-04-01T08:24:45.967606Z', 'version': 11, 'createDate': '0001-01-01T00:00:00'}],
 'count': 7}
    #  если нужна информация о ПУ по техническому или серийному номеру
    elif url_mark == "url5":
        val_sutp={
                "techNumber": 100025776,
                "techNumberStr": "100025776",
                "packId": 120,
                "pack": None,
                "number": "240100080015919",
                "orderNumber": 126,
                "order": {
                    "number": 126,
                    "numberStr": "00000126",
                    "customerName": "Энергоинновации",
                    "readyDate": "2024-04-30T15:00:00Z",
                    "statusCode": 0,
                    "statusName": None,
                    "employeeId": 1005,
                    "employee": None,
                    "deviceDoneCount": 0,
                    "warrantyPeriod": 5,
                    "orderName": "5119 Энергоинновации, ПУ 1ф_GSM- 5200 шт, ПУ 3ф_GSM- 6647 шт",
                    "documentNumber": "5119",
                    "description": None,
                    "responsibleManager": "Косматкина Е.",
                    "shippingPoint": "Энергоинновации",
                    "createDate": "2024-03-12T06:21:41Z",
                    "passwordTypeLLSId": 0,
                    "passwordTypeHLSId": 0,
                    "assignedPasswordLLS": None,
                    "assignedPasswordHLS": None,
                    "defectCount": None,
                    "passwordTypeLLS": None,
                    "passwordTypeHLS": None,
                    "timeZoneNumber": 3,
                    "timeZone": None,
                    "orderDetails": None,
                    "orderResources": None
                },
                "deviceStatusId": 10,
                "deviceStatus": None,
                "deviceStatuses": [
                    {
                    "id": 1,
                    "name": "Новый",
                    "description": None,
                    "priority": 1,
                    "isActive": True
                    },
                    {
                    "id": 2,
                    "name": "Сборка пройдена",
                    "description": None,
                    "priority": 2,
                    "isActive": True
                    },
                    {
                    "id": 3,
                    "name": "Пайка пройдена",
                    "description": None,
                    "priority": 3,
                    "isActive": True
                    },
                    {
                    "id": 4,
                    "name": "Прошивка пройдена",
                    "description": None,
                    "priority": 4,
                    "isActive": True
                    },
                    {
                    "id": 5,
                    "name": "Функциональное тестирование пройдено",
                    "description": None,
                    "priority": 5,
                    "isActive": True
                    },
                    {
                    "id": 6,
                    "name": "Калибровка пройдена",
                    "description": None,
                    "priority": 6,
                    "isActive": True
                    },
                    {
                    "id": 7,
                    "name": "Гравировка пройдена",
                    "description": None,
                    "priority": 8,
                    "isActive": True
                    },
                    {
                    "id": 10,
                    "name": "В ремонте на линии",
                    "description": None,
                    "priority": None,
                    "isActive": False
                    },
                    {
                    "id": 11,
                    "name": "Крышка закрыта",
                    "description": None,
                    "priority": 7,
                    "isActive": True
                    },
                    {
                    "id": 399,
                    "name": "Отправлен в ремонт",
                    "description": None,
                    "priority": None,
                    "isActive": False
                    }
                ],
                "deviceTypeId": 9,
                "deviceType": {
                    "id": 9,
                    "code": "0008",
                    "name": "i-prom.1-3-1/2-M-R-Y-Y",
                    "description": None,
                    "isActive": True,
                    "matchedVoltage": None,
                    "maxCurrent": 80,
                    "generalDeviceTypeId": 1,
                    "generalDeviceType": None
                },
                "generalDeviceTypeId": 1,
                "generalDeviceType": {
                    "id": 1,
                    "name": "1Ф",
                    "description": None,
                    "formOfDeviceTypeId": "d317f4ed-7d67-40e5-93c7-800526b075fa"
                },
                "technologyTypeId": 9,
                "technologyType": None,
                "employeeId": 379,
                "employee": None,
                "developmentId": 1,
                "development": None,
                "boxId": None,
                "box": None,
                "boxOrderingNumber": None,
                "defectDescription": None,
                "firmwareVersion": None,
                "wasOnRepairRecently": False,
                "validFrom": "2024-04-03T10:43:35.075029Z",
                "version": 17
                }
        # val_sutp={'techNumber': 100070313, 
        #         'techNumberStr': '100070313', 
        #         'packId': 196,
        #         'pack': None, 
        #         'number': '240100080015919',
        #         'orderNumber': 62, 
        #         'order': {
        #         'number': 62,
        #         'numberStr': '00000062',
        #         'customerName': 'БашкирЭнерго',
        #         'readyDate': '2023-12-31T06:00:00Z', 
        #         'statusCode': 2, 
        #         'statusName': None, 
        #         'employeeId': 260, 
        #         'employee': None,
        #         'deviceDoneCount': 0, 
        #         'orderName': '4996 БашкирЭнерго', 
        #         'documentNumber': None, 
        #         'description': None, 
        #         'responsibleManager': None, 
        #         'shippingPoint': None, 
        #         'createDate': '2023-12-13T17:03:38Z',
        #         'passwordTypeLLSId': 0,
        #         'passwordTypeHLSId': 0, 
        #         'assignedPasswordLLS': None,
        #         'assignedPasswordHLS': None, 
        #         'defectCount': None, 
        #         'passwordTypeLLS': None,
        #         'passwordTypeHLS': None, 
        #         'orderDetails': None, 
        #         'orderResources': None
        #         }, 
        #         'deviceStatusId': 18, 
        #         'deviceStatus': None, 
        #         'deviceStatuses': [],
        #         'deviceTypeId': 31,
        #         'deviceType': {
        #         'id': 31, 
        #         'code': '0114', 
        #         'name': 'i-prom.3-3-1-1/2-S-RG-Y-Y', 
        #         'description': None,
        #         'maxCurrent': 100, 
        #         'formOfDeviceTypeId': 'e2500990-0b2c-48b1-be3c-da84bdf3f7eb',
        #         'productTypeId': '4ec3404a-2a3c-4a71-ad5f-61e536726935'
        #         }, 
        #         'technologyTypeId': 30, 
        #         'technologyType': None, 
        #         'employeeId': 281,
        #         'employee': None, 
        #         'developmentId': 1,
        #         'development': None, 
        #         'boxId': '2b532720-4aa3-477f-a1da-e67575c1a611',
        #         'box': {
        #         'id': '2b532720-4aa3-477f-a1da-e67575c1a611', 
        #         'number': 1340,
        #         'orderNumber': 62, 
        #         'order': None,
        #         'packed': True, 
        #         'isActive': True, 
        #         'createDate': '2024-05-13T13:10:24.963872Z', 
        #         'updateDate': None
        #         }, 
        #         'boxOrderingNumber': 4, 
        #         'defectDescription': None, 
        #         'firmwareVersion': '4.10.276',
        #         'wasOnRepairRecently': False, 
        #         'validFrom': '2024-05-13T13:51:21.743456Z',
        #         'version': 15
        #         } 
    #  весь список статусов ПУ на 07.05.2024
    elif url_mark == "url6":
        true=True
        false=False
        null=None
        val_sutp=[
            {"id":1,"name":"Новый","description":null,"priority":1,"isActive":true},
            {"id":2,"name":"Сборка пройдена","description":null,"priority":2,"isActive":true},
            {"id":3,"name":"Пайка пройдена","description":null,"priority":3,"isActive":true},
            {"id":4,"name":"Прошивка пройдена","description":null,"priority":4,"isActive":true},
            {"id":5,"name":"Функциональное тестирование пройдено","description":null,"priority":5,"isActive":true},
            {"id":6,"name":"Калибровка пройдена","description":null,"priority":6,"isActive":true},
            {"id":11,"name":"Крышка закрыта","description":null,"priority":7,"isActive":true},
            {"id":7,"name":"Гравировка пройдена","description":null,"priority":8,"isActive":true},
            {"id":21,"name":"ОТК пройден","description":null,"priority":9,"isActive":true},
            {"id":8,"name":"Стыковка и паспортизация пройдены","description":null,"priority":10,"isActive":true},
            {"id":14,"name":"Поверка пройдена","description":null,"priority":11,"isActive":true},
            {"id":18,"name":"Упаковка пройдена","description":null,"priority":12,"isActive":true},
            {"id":22,"name":"Конфигурация пройдена","description":null,"priority":13,"isActive":true},
            {"id":23,"name":"Генерация пароля пройдена","description":null,"priority":14,"isActive":true},
            {"id":401,"name":"Неисправимый брак из ремонтного отдела","description":null,"priority":null,"isActive":false},
            {"id":10,"name":"В ремонте на линии","description":null,"priority":null,"isActive":false},
            {"id":400,"name":"Неисправимый брак из ремонта на линии","description":null,"priority":null,"isActive":false},
            {"id":24,"name":"Привязан к заказ-наряду","description":null,"priority":null,"isActive":true},
            {"id":9,"name":"Финальная проверка пройдена","description":null,"priority":null,"isActive":false},
            {"id":399,"name":"Дефект","description":null,"priority":null,"isActive":false},
            {"id":12,"name":"Окончательная проверка","description":null,"priority":null,"isActive":false},
            {"id":17,"name":"Стыковка GSM","description":null,"priority":null,"isActive":false},
            {"id":16,"name":"Закрытие крышки клеммой колодки","description":null,"priority":null,"isActive":false},
            {"id":15,"name":"Закрытие интерфейсной крышки","description":null,"priority":null,"isActive":false},
            {"id":13,"name":"Печать паспорта","description":null,"priority":null,"isActive":false},
            {"id":20,"name":"Специальный статус","description":null,"priority":null,"isActive":false},
            {"id":19,"name":"Отгрузка","description":null,"priority":null,"isActive":true},
            {"id":1000,"name":"Неизвестный статус","description":null,"priority":null,"isActive":false},
            {"id":390,"name":"Отправлен в ремонтный отдел","description":null,"priority":null,"isActive":false},
            {"id":391,"name":"Принят в ремонтный отдел","description":null,"priority":null,"isActive":false},
            {"id":392,"name":"В ремонте в ремонтном отделе","description":null,"priority":null,"isActive":false},
            {"id":393,"name":"Отправлен из ремонтного отдела","description":null,"priority":null,"isActive":false},
            {"id":394,"name":"Принят из ремонтного отдела","description":null,"priority":null,"isActive":false}
            ]
    # информации о пользователе по табельному номеру
    elif url_mark=="url7":
        null=None
        val_sutp = {"id": 234, "idStr": "2.0234", "name": "Олег", 
            "surName": "Демин", "secondName": "Владимирович", 
            "phone": null, "role": "admin", "positionId": 2, 
            "position": null}
    # количество устройств, прошедших через указанный
    #   этап (21) сегодня
    elif url_mark == "url8":
        val_sutp = [{'date': '2024-05-02T00:00:00Z', 'typeId': 31, 
                'statusId': 21, 'count': 328},
            {'date': '2024-05-02T00:00:00Z', 'typeId': 9,
                'statusId': 21, 'count': 501},
            {'date': '2024-05-02T00:00:00Z', 'typeId': 35,
                'statusId': 21, 'count': 26},
            {'date': '2024-05-02T00:00:00Z',
                'typeId': 35, 'statusId': 21, 'count': 1},
            {'date': '2024-05-02T00:00:00Z', 'typeId': 31, 
                'statusId': 21, 'count': 1}]
    # список ПУ, с которыми работал указанный работник
    elif url_mark == "url9":
        val_sutp = {'status': 'Success', 'message': 'Запрос Get успешно выполнен',
            'items': [
            {'techNumber': 100028866, 'techNumberStr': '100028866', 'packId': 126, 
                'number': '240101140000668', 'deviceStatusId': 21,
                'deviceStatus':
                {'id': 21, 'name': 'ОТК пройден'},
                'deviceTypeId': 31, 'technologyTypeId': 30, 'employeeId': 295,
                'employee':
                {'id': 295, 'idStr': '2.0295', 'name': 'Владислав', 
                'surName': 'Васильев', 'secondName': 'Валерьевич', 
                'role': 'user', 'positionId': 2},
                'developmentId': 1, 'validFrom': '2024-05-08T12:48:03.30578Z', 
                'validTo': '0001-01-01T00:00:00', 'version': 13, 
                'createDate': '0001-01-01T00:00:00'},
            {'techNumber': 100028866, 'techNumberStr': '100028866', 'packId': 126, 
                'number': '240101140000668', 'deviceStatusId': 7,
                'deviceStatus':
                {'id': 7, 'name': 'Гравировка пройдена'},
                'deviceTypeId': 31, 'technologyTypeId': 30, 'employeeId': 295,
                'employee':
                {'id': 295, 'idStr': '2.0295', 'name': 'Владислав', 
                'surName': 'Васильев', 'secondName': 'Валерьевич', 
                'role': 'user', 'positionId': 2},
                'developmentId': 1,
                'development':
                {'id': 1, 'name': 'Главное предприятие'},
                'validFrom': '2024-05-08T12:45:36.311296Z', 
                'validTo': '2024-05-08T12:48:03.306444Z', 'version': 12, 
                'createDate': '0001-01-01T00:00:00'},
            {'techNumber': 100025524, 'techNumberStr': '100025524', 
            'packId': 120, 'number': '240101140000074', 'deviceStatusId': 10, 
            'deviceStatus': {'id': 10, 'name': 'В ремонте на линии'}, 
            'deviceTypeId': 31, 'technologyTypeId': 30, 'employeeId': 295, 
            'employee': {'id': 295, 'idStr': '2.0295', 'name': 'Владислав', 
            'surName': 'Васильев', 'secondName': 'Валерьевич', 'role': 'user', 
            'positionId': 2}, 'developmentId': 1, 
            'validFrom': '2024-05-08T12:42:09.2281Z', 
            'validTo': '0001-01-01T00:00:00', 'version': 14, 
            'createDate': '0001-01-01T00:00:00'}, 
            {'techNumber': 100025524, 'techNumberStr': '100025524', 
            'packId': 120, 'number': '240101140000074', 'deviceStatusId': 7, 
            'deviceStatus': {'id': 7, 'name': 'Гравировка пройдена'}, 
            'deviceTypeId': 31, 'technologyTypeId': 30, 'employeeId': 295, 
            'employee': {'id': 295, 'idStr': '2.0295', 'name': 'Владислав', 
            'surName': 'Васильев', 'secondName': 'Валерьевич', 'role': 'user', 
            'positionId': 2}, 'developmentId': 1, 
            'development': {'id': 1, 'name': 'Главное предприятие'}, 
            'validFrom': '2024-05-08T12:41:19.251206Z', 
            'validTo': '2024-05-08T12:42:09.228862Z', 'version': 13, 
            'createDate': '0001-01-01T00:00:00'}, {'techNumber': 100030292, 
            'techNumberStr': '100030292', 'packId': 128, 
            'number': '240101140000763', 'deviceStatusId': 21, 
            'deviceStatus': {'id': 21, 'name': 'ОТК пройден'}, 
            'deviceTypeId': 31, 'technologyTypeId': 30,
            'employeeId': 295, 'employee': {'id': 295, 'idStr': '2.0295', 
            'name': 'Владислав', 'surName': 'Васильев', 'secondName': 'Валерьевич',
             'role': 'user', 'positionId': 2}, 'developmentId': 1, 
             'validFrom': '2024-05-08T12:38:05.841276Z', 
             'validTo': '0001-01-01T00:00:00', 'version': 13, 
             'createDate': '0001-01-01T00:00:00'}, 
             {'techNumber': 100030292, 'techNumberStr': '100030292', 
             'packId': 128, 'number': '240101140000763', 'deviceStatusId': 7, 
             'deviceStatus': {'id': 7, 'name': 'Гравировка пройдена'}, 
             'deviceTypeId': 31, 'technologyTypeId': 30, 'employeeId': 295,
              'employee': {'id': 295, 'idStr': '2.0295', 'name': 'Владислав', 
              'surName': 'Васильев', 'secondName': 'Валерьевич', 'role': 'user', 
              'positionId': 2}, 'developmentId': 1, 
              'development': {'id': 1, 'name': 'Главное предприятие'}, 
              'validFrom': '2024-05-08T12:36:49.90538Z', 
              'validTo': '2024-05-08T12:38:05.841895Z', 'version': 12, 
              'createDate': '0001-01-01T00:00:00'}, 
              {'techNumber': 100028961, 'techNumberStr': '100028961', 
              'packId': 126, 'number': '240101140001118', 'deviceStatusId': 21, 
              'deviceStatus': {'id': 21, 'name': 'ОТК пройден'}, 
              'deviceTypeId': 31, 'technologyTypeId': 30, 'employeeId': 295, 
              'employee': {'id': 295, 'idStr': '2.0295', 'name': 'Владислав', 
                'surName': 'Васильев', 'secondName': 'Валерьевич', 
                'role': 'user', 'positionId': 2}, 'developmentId': 1, 
                'validFrom': '2024-05-08T12:34:59.693031Z', 
                'validTo': '0001-01-01T00:00:00', 'version': 13, 
                'createDate': '0001-01-01T00:00:00'}, 
                {'techNumber': 100028961, 'techNumberStr': '100028961', 
                'packId': 126, 'number': '240101140001118', 'deviceStatusId': 7, 
                'deviceStatus': {'id': 7, 'name': 'Гравировка пройдена'}, 
                'deviceTypeId': 31, 'technologyTypeId': 30, 'employeeId': 295, 
                'employee': {'id': 295, 'idStr': '2.0295', 'name': 'Владислав', 
                'surName': 'Васильев', 'secondName': 'Валерьевич', 'role': 'user', 
                'positionId': 2}, 'developmentId': 1, 
                'development': {'id': 1, 'name': 'Главное предприятие'}, 
                'validFrom': '2024-05-08T12:34:16.830052Z', 
                'validTo': '2024-05-08T12:34:59.693815Z', 'version': 12, 
                'createDate': '0001-01-01T00:00:00'},
                 {'techNumber': 100025548, 'techNumberStr': '100025548', 
                 'packId': 120, 'number': '240101140000053', 
                 'deviceStatusId': 21, 'deviceStatus': {'id': 21, 
                 'name': 'ОТК пройден'}, 'deviceTypeId': 31, 
                 'technologyTypeId': 30, 'employeeId': 295, 
                 'employee': {'id': 295, 'idStr': '2.0295', 'name': 'Владислав', 
                 'surName': 'Васильев', 'secondName': 'Валерьевич', 'role': 'user',
                  'positionId': 2}, 'developmentId': 1, 
                  'validFrom': '2024-05-08T12:22:07.509502Z', 
                  'validTo': '0001-01-01T00:00:00', 'version': 14, 
                  'createDate': '0001-01-01T00:00:00'}, 
                  {'techNumber': 100025548, 'techNumberStr': '100025548', 
                  'packId': 120, 'number': '240101140000053', 'deviceStatusId': 7, 
                  'deviceStatus': {'id': 7, 'name': 'Гравировка пройдена'}, 
                  'deviceTypeId': 31, 'technologyTypeId': 30, 'employeeId': 295,
                   'employee': {'id': 295, 'idStr': '2.0295', 'name': 'Владислав', 
                   'surName': 'Васильев', 'secondName': 'Валерьевич', 'role': 'user',
                    'positionId': 2}, 'developmentId': 1, 
                    'development': {'id': 1, 'name': 'Главное предприятие'}, 
                    'validFrom': '2024-05-08T12:17:31.702368Z', 
                    'validTo': '2024-05-08T12:22:07.510186Z', 'version': 13, 
                    'createDate': '0001-01-01T00:00:00'}], 
                    'count': 10}
    # информация о заказе
    elif url_mark == "url10":
        val_sutp = {'number': 126,
                    'numberStr': '00000126',
                    'customerName': '5119 Энергоинновации, ПУ 1ф_GSM- 5200 шт, ПУ 3ф_GSM- 6647 шт',
                    'readyDate': '2024-04-30T09:00:00Z',
                    'statusCode': 2,
                    'statusName': 'В процессе выполнения',
                    'employeeId': 181,
                    'employee':
                    {'id': 181,
                     'idStr': '3.0181',
                     'name': 'Ринас',
                     'surName': 'Сайфуллин',
                     'secondName': 'Ралифович',
                     'phone': None,
                     'role': 'admin',
                     'positionId': 3,
                     'position': None},
                    'deviceDoneCount': 0,
                    'orderName': '5119 Энергоинновации, ПУ 1ф_GSM- 5200 шт, ПУ 3ф_GSM- 6647 шт',
                    'documentNumber': None,
                    'description': None,
                    'responsibleManager': 'Косматкина Е.',
                    'shippingPoint': 'Энергоинновации',
                    'createDate': '2024-03-12T00:21:41Z',
                    'passwordTypeLLSId': 0,
                    'passwordTypeHLSId': 0,
                    'assignedPasswordLLS': None,
                    'assignedPasswordHLS': None,
                    'defectCount': 38,
                    'passwordTypeLLS':
                    {'id': 0,
                     'name': 'Заводской пароль'},
                    'passwordTypeHLS':
                    {'id': 0, 'name': 'Заводской пароль'},
                    'timeZoneNumber': 3,
                    'timeZone':
                    {'number': 3,
                        'name': 'GMT +3 (Москва)'},
                    'orderDetails': None, 
                    'orderResources': [{'id': '716f70af-f95d-4f09-a3e9-ec2669bc848c', 
                    'count': 5200, 'doneCount': 5175, 'orderNumber': 126, 
                    'resourcePackId': '5cd8d866-c2b1-4836-8f40-7b099b393ec7',
                     'productId': 'f29e9397-7e98-4669-beb9-bb792427e66c', 
                     'order': None, 'product': {'id': 'f29e9397-7e98-4669-beb9-bb792427e66c', 
                     'name': '1-phase MKD with 2G Modem', 'gsmTypeId': 5, 
                     'deviceTypeId': 9, 'meterRndId': 'dc0ac064-4721-4ae9-addf-75771807f017', 
                     'communicationModeleRndId': 'efc07d5e-ffc7-499d-8198-6f72cffdb07b', 
                     'devType': '0008', 'gsmType': {'id': 5, 'name': 'MC.1-M-G', 
                     'code': '1004', 'description': None, 
                     'formOfDeviceTypeId': '7a6c5f33-d048-4d5b-94d4-a89e52cf7fa1',
                      'format': None, 'productTypeId': None}, 
                      'deviceType': {'id': 9, 'code': '0008',
                    'name': 'i-prom.1-1-1/2-M-RM-Y-Y', 'description': None, 
                    'maxCurrent': 100, 
                    'formOfDeviceTypeId': 'd317f4ed-7d67-40e5-93c7-800526b075fa', 
                    'productTypeId': 'e41ab824-ffeb-428c-8660-91c511eb7d0e'}, 
                    'meterRnd': {'id': 'dc0ac064-4721-4ae9-addf-75771807f017', 
                    'name': 'MKD_v5', 'productTypeId': 'e41ab824-ffeb-428c-8660-91c511eb7d0e',
                    'productType': None}, 
                    'communicationModeleRnd': {'id': 'efc07d5e-ffc7-499d-8198-6f72cffdb07b', 
                    'name': 'GSM_MKD_v5', 'productTypeId': '53bd4628-eab2-47a9-908c-c20a910e4d27', 
                    'productType': None}, 'orderResources': None}, 
                    'resourcePack': {'id': '5cd8d866-c2b1-4836-8f40-7b099b393ec7', 
                    'name': 'Ресурс_Пак_1ф_МС', 
                    'resources': [{'id': '54f512a7-1b49-4d7a-b190-9a9a73583492', 
                    'name': 'Шаблон гравера MC 1ph Set5', 
                    'description': 'Шаблон гравера для МС 1-фазных ПУ 5 штук', 
                    'version': '1', 
                    'url': 'http://192.168.14.13:9000/promenergo-document-manager/resources/Laser_marking_template_communication_module/GSM_MKD_v5/1/54f512a7-1b49-4d7a-b190-9a9a73583492/Шаблон-гравера_GSM_1ph_Set5.ezd', 
                    'checksum': '5a33a817eb8613ae6216b5a6b84e5ef0e19cf93767ccd1fa008a21efaef244a2', 
                    'resourceTypeId': '9f7b0ac4-d8f0-451d-be9d-ef18b97766dd', 'createEmployeeId': 1008, 
                    'rndId': 'efc07d5e-ffc7-499d-8198-6f72cffdb07b', 'resourceType': None, 
                    'createEmployee': None, 'rnd': None, 'createDate': '2024-04-25T09:12:44.828906Z', 
                    'updateDate': '2024-04-25T09:12:44.828906Z'}, 
                    {'id': '623a0b4a-0481-45c3-902b-a16362a19b02', 'name': 'Шаблон гравера 1ph', 
                    'description': 'Шаблон гравера для 1-фазных ПУ без МС без лого', 
                    'version': '1', 
                    'url': 'http://192.168.14.13:9000/promenergo-document-manager/resources/Laser_marking_template_meter/MKD_v5/1/623a0b4a-0481-45c3-902b-a16362a19b02/Шаблон-гравера_1ph.ezd', 
                    'checksum': '37e6bcdbb3ad209a83176ba9e04363f855132393eedfe339e0da86384de63ff0', 
                    'resourceTypeId': '6b40a489-d4b9-4d0c-9590-88cf8c8b0b04', 
                    'createEmployeeId': 1008, 'rndId': 'dc0ac064-4721-4ae9-addf-75771807f017', 
                    'resourceType': None, 'createEmployee': None, 'rnd': None, 
                    'createDate': '2024-04-25T09:11:59.553412Z', 
                    'updateDate': '2024-04-25T09:11:59.553412Z'}]}}, 
                    {'id': 'd5ad7ff5-89b2-4328-bd84-8f63227a01e3', 'count': 6647, 
                    'doneCount': 3112, 'orderNumber': 126, 'resourcePackId': None, 
                    'productId': '402b7c93-adc5-4b86-814c-62d86410b8af', 'order': None, 
                    'product': {'id': '402b7c93-adc5-4b86-814c-62d86410b8af', 
                    'name': '3-phase direct Monoblock with 2G Modem', 'gsmTypeId': 13, 
                    'deviceTypeId': 31, 'meterRndId': '6f08970b-708f-40d4-8967-d2583975e8fc', 
                    'communicationModeleRndId': '47ad4204-8bbf-4c78-a657-d3474487d147', 
                    'devType': '0114', 'gsmType': {'id': 13, 'name': 'MC.3-P-G', 'code': '1012', 
                    'description': None, 'formOfDeviceTypeId': 'd31f0942-a66d-4e09-b428-33c573f88aba', 
                    'format': None, 'productTypeId': None}, 
                    'deviceType': {'id': 31, 'code': '0114', 'name': 'i-prom.3-3-1-1/2-S-RG-Y-Y', 
                    'description': None, 'maxCurrent': 100, 
                    'formOfDeviceTypeId': 'e2500990-0b2c-48b1-be3c-da84bdf3f7eb', 
                    'productTypeId': '4ec3404a-2a3c-4a71-ad5f-61e536726935'}, 
                    'meterRnd': {'id': '6f08970b-708f-40d4-8967-d2583975e8fc', 
                    'name': '3ph_v1', 'productTypeId': '4ec3404a-2a3c-4a71-ad5f-61e536726935', 
                    'productType': None}, 'communicationModeleRnd': {'id': '47ad4204-8bbf-4c78-a657-d3474487d147', 
                    'name': 'GSM_3ph_v1', 'productTypeId': '53bd4628-eab2-47a9-908c-c20a910e4d27', 
                    'productType': None}, 'orderResources': None}, 'resourcePack': None}]}


    # выйдем с успехом и возвратим тестовые данные
    return ["1", "Тестовые данные сформированы.", val_sutp]
